        set(h.element_select_popup,"value",1);
        set(h.adv_Gt_T_match_rb,"value",1);
        advF=get(h.advanced_enable_checkbox, "value");
        h.z_in_element_select_popup;
        G_T_flag=get(h.adv_Gt_T_match_rb,"value");
        resetGt=get(h.adv_Gt_reset_rb,"value");
        qflag=get(h.Q_enable_checkbox,"value");
        menu_val=get(h.element_select_popup,"value");
        back=get(h.go_back_one_pushbutton,"value");
        presetsF=get(h.enable_presets_checkbox,"value");
